### ISSUE TITLE
Could you give support to 10.8

### ISSUE THREAD

**Issue by alan42521** [mos9527/evbunpack#8]
It seems there is a problem decrypting version of 10.8

**Comment by mos9527** [comment]
There doesn't seem to be any issues unpacking [the test file(s) packed with EVB 10.80](https://github.com/mos9527/evbunpack/blob/main/tests/x64_PackerTestApp_packed_20240613.exe). Please provide me with more information regarding your problem (e.g. unpacker log output, or, if possible, the binary itself) Here are some of the flags you should try to use:
- `--log-level DEBUG`
- `--pe 10_70`

**Comment by alan42521** [comment]
[
![捕获](https://github.com/mos9527/evbunpack/assets/108172351/eafc5fc9-f57c-4041-a665-4f76a7b5fdc0)
](url)

**Comment by mos9527** [comment]
Your executable is possibly not packed with Engima Virtual Box, or additional packer/compressor is used.(since the `EVB` magic would always be present otherwise).
You can double check this with [Die](https://github.com/horsicq/Detect-It-Easy).
You can try adding the flag `--ignore-fs` to only unpack the executable and ignore the filesystem check. However, this would probably fail as well.
Note that this unpacker only works with Enigma **Virtual Box**. Not the Enigma **Protector**.
